export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_COUNTRIES_BY_FILTER = "GET_COUNTRIES_BY_FILTER";
export const GET_FILTER_BY_SEACH = "GET_FILTER_BY_SEACH";

export const GET_COUNTRIES_ID = "GET_COUNTRIES_ID";
export const POST_ACT = "POST_ACT ";
export const GET_COUNTRIES_ASC = "GET_COUNTRIES_ASC";
export const GET_COUNTRIES_DESC = "GET_COUNTRIES_DESC";
export const GET_COUNTRIES_Mayor = "GET_COUNTRIES_Mayor";
export const GET_COUNTRIES_Menor = "GET_COUNTRIES_Menor";
export const GET_IDS = "GET_IDS";

export const GET_ALL_ACT = "GET_ALL_ACT";
export const FIL_ACT_TEMP = "FIL_ACT_TEMP";
export const FIL_ACT_BUSQUEDA= "FIL_ACT_BUSQUEDA";
export const FIL_ACT_TEMP_IND= "FIL_ACT_TEMP_IND";
export const FIL_ACT_BUSQUEDA_IND= "FIL_ACT_BUSQUEDA_IND";
export const GET_ALL_ACT_IND= "GET_ALL_ACT_IND";

export const FILTRO_CONTINENTE_ASIA= "FILTRO_CONTINENTE_ASIA"
export const FILTRO_CONTINENTE_AFRICA= "FILTRO_CONTINENTE_AFRICA"
export const FILTRO_CONTINENTE_AMERICAS= "FILTRO_CONTINENTE_AMERICAS"
export const FILTRO_CONTINENTE_ANTARCTIC= "FILTRO_CONTINENTE_ANTARCTIC"
export const FILTRO_CONTINENTE_EUROPE= "FILTRO_CONTINENTE_EUROPE"
export const FILTRO_CONTINENTE_OCEANIA= "FILTRO_CONTINENTE_OCEANIA"
export const FILTER_SEACH_ACT= "FILTER_SEACH_ACT"







export const FILTRO_ACTIVIDAD_VERANO= "FILTRO_ACTIVIDAD_VERANO"
export const FILTRO_ACTIVIDAD_INVIERNO= "FILTRO_ACTIVIDAD_INVIERNO"
export const FILTRO_ACTIVIDAD_OTOÑO= "FILTRO_ACTIVIDAD_OTOÑO"
export const FILTRO_ACTIVIDAD_PRIMAVERA= "FILTRO_ACTIVIDAD_PRIMAVERA"

export const GET_ACTIVIDAD_BY_FILTER= "GET_ACTIVIDAD_BY_FILTER"




// asia: "Asia",
// africa: "Africa",
// américas: "Americas",
// antarctic: "Antarctic",
// europe: "Europe",
// oceania: "Oceania",